"""hosts: enrollment_token_expires_at + enrolled_at

Revision ID: 7040cb7e2799
Revises: 89fb15616be2
Create Date: 2026-05-10 22:35:13.772911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7040cb7e2799'
down_revision: Union[str, Sequence[str], None] = '89fb15616be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('enrollment_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hosts', sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'enrolled_at')
    op.drop_column('hosts', 'enrollment_token_expires_at')
    # ### end Alembic commands ###
