"""host_packages + host_vulnerabilities

Revision ID: 83e4d681f6e1
Revises: 7fcb043197cb
Create Date: 2026-05-11 00:53:39.967712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e4d681f6e1'
down_revision: Union[str, Sequence[str], None] = '7fcb043197cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('arch', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'name', 'arch', name='uq_host_package_name_arch')
    )
    op.create_index(op.f('ix_host_packages_host_id'), 'host_packages', ['host_id'], unique=False)
    op.create_index(op.f('ix_host_packages_name'), 'host_packages', ['name'], unique=False)
    op.create_table('host_vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('installed_version', sa.String(length=255), nullable=False),
    sa.Column('fixed_version', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'cve_id', 'package_name', name='uq_host_cve_pkg')
    )
    op.create_index(op.f('ix_host_vulnerabilities_cve_id'), 'host_vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_host_vulnerabilities_host_id'), 'host_vulnerabilities', ['host_id'], unique=False)
    op.create_index(op.f('ix_host_vulnerabilities_severity'), 'host_vulnerabilities', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_vulnerabilities_severity'), table_name='host_vulnerabilities')
    op.drop_index(op.f('ix_host_vulnerabilities_host_id'), table_name='host_vulnerabilities')
    op.drop_index(op.f('ix_host_vulnerabilities_cve_id'), table_name='host_vulnerabilities')
    op.drop_table('host_vulnerabilities')
    op.drop_index(op.f('ix_host_packages_name'), table_name='host_packages')
    op.drop_index(op.f('ix_host_packages_host_id'), table_name='host_packages')
    op.drop_table('host_packages')
    # ### end Alembic commands ###
