"""host kernel arch location

Revision ID: 94c2ac6b5b34
Revises: baf5f2039064
Create Date: 2026-05-11 18:28:37.597497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c2ac6b5b34'
down_revision: Union[str, Sequence[str], None] = 'baf5f2039064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('kernel', sa.String(length=100), nullable=True))
    op.add_column('hosts', sa.Column('arch', sa.String(length=50), nullable=True))
    op.add_column('hosts', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'location')
    op.drop_column('hosts', 'arch')
    op.drop_column('hosts', 'kernel')
    # ### end Alembic commands ###
