"""host stats columns

Revision ID: baf5f2039064
Revises: 2bbe18a54cc5
Create Date: 2026-05-11 14:57:18.303446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf5f2039064'
down_revision: Union[str, Sequence[str], None] = '2bbe18a54cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('hosts', sa.Column('cpu_count', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('load_avg_1m', sa.Float(), nullable=True))
    op.add_column('hosts', sa.Column('mem_used_bytes', sa.BigInteger(), nullable=True))
    op.add_column('hosts', sa.Column('mem_total_bytes', sa.BigInteger(), nullable=True))
    op.add_column('hosts', sa.Column('disk_used_bytes', sa.BigInteger(), nullable=True))
    op.add_column('hosts', sa.Column('disk_total_bytes', sa.BigInteger(), nullable=True))
    op.add_column('hosts', sa.Column('uptime_seconds', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'uptime_seconds')
    op.drop_column('hosts', 'disk_total_bytes')
    op.drop_column('hosts', 'disk_used_bytes')
    op.drop_column('hosts', 'mem_total_bytes')
    op.drop_column('hosts', 'mem_used_bytes')
    op.drop_column('hosts', 'load_avg_1m')
    op.drop_column('hosts', 'cpu_count')
    op.drop_column('hosts', 'ip_address')
    # ### end Alembic commands ###
