"""host admin panel counts

Revision ID: c35ab947eb39
Revises: 746dbef1e94d
Create Date: 2026-05-11 18:51:32.348068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35ab947eb39'
down_revision: Union[str, Sequence[str], None] = '746dbef1e94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('clamav_installed', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('clamav_version', sa.String(length=255), nullable=True))
    op.add_column('hosts', sa.Column('clamav_db_age_days', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('services_running', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('services_failed', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('packages_upgradable', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('listening_ports', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('cron_jobs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'cron_jobs')
    op.drop_column('hosts', 'listening_ports')
    op.drop_column('hosts', 'packages_upgradable')
    op.drop_column('hosts', 'services_failed')
    op.drop_column('hosts', 'services_running')
    op.drop_column('hosts', 'clamav_db_age_days')
    op.drop_column('hosts', 'clamav_version')
    op.drop_column('hosts', 'clamav_installed')
    # ### end Alembic commands ###
