# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AgentService — RPC bidirecional entre agente (host) e server.
    mTLS obrigatório (ADR-005). Cada agente tem cert único.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/sentinelbr.agent.v1.AgentService/Enroll',
                request_serializer=agent__pb2.EnrollRequest.SerializeToString,
                response_deserializer=agent__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/sentinelbr.agent.v1.AgentService/Heartbeat',
                request_serializer=agent__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=agent__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.stream_stream(
                '/sentinelbr.agent.v1.AgentService/StreamEvents',
                request_serializer=agent__pb2.Event.SerializeToString,
                response_deserializer=agent__pb2.EventAck.FromString,
                _registered_method=True)
        self.SubmitInventory = channel.unary_unary(
                '/sentinelbr.agent.v1.AgentService/SubmitInventory',
                request_serializer=agent__pb2.InventoryReport.SerializeToString,
                response_deserializer=agent__pb2.InventoryAck.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService — RPC bidirecional entre agente (host) e server.
    mTLS obrigatório (ADR-005). Cada agente tem cert único.
    """

    def Enroll(self, request, context):
        """Enroll é a primeira chamada do agente após instalação.
        Retorna host_id e config inicial.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat — agente manda status a cada N segundos (default 30).
        Server pode mandar comandos no response (BlockIP, RunCheck, etc.).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request_iterator, context):
        """StreamEvents — fluxo contínuo de eventos coletados (logs, alerts).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInventory(self, request, context):
        """SubmitInventory — agente envia lista de pacotes instalados pra cross-ref
        com base de vulnerabilidades (OSV/NVD).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=agent__pb2.EnrollRequest.FromString,
                    response_serializer=agent__pb2.EnrollResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=agent__pb2.HeartbeatRequest.FromString,
                    response_serializer=agent__pb2.HeartbeatResponse.SerializeToString,
            ),
            'StreamEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=agent__pb2.Event.FromString,
                    response_serializer=agent__pb2.EventAck.SerializeToString,
            ),
            'SubmitInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInventory,
                    request_deserializer=agent__pb2.InventoryReport.FromString,
                    response_serializer=agent__pb2.InventoryAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinelbr.agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinelbr.agent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService — RPC bidirecional entre agente (host) e server.
    mTLS obrigatório (ADR-005). Cada agente tem cert único.
    """

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelbr.agent.v1.AgentService/Enroll',
            agent__pb2.EnrollRequest.SerializeToString,
            agent__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelbr.agent.v1.AgentService/Heartbeat',
            agent__pb2.HeartbeatRequest.SerializeToString,
            agent__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sentinelbr.agent.v1.AgentService/StreamEvents',
            agent__pb2.Event.SerializeToString,
            agent__pb2.EventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelbr.agent.v1.AgentService/SubmitInventory',
            agent__pb2.InventoryReport.SerializeToString,
            agent__pb2.InventoryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
