// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // token one-time gerado no server
	Os              *OSInfo                `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname        string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetOs() *OSInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                        // UUID gerado pelo server
	ClientCertPem string                 `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"` // cert assinado pela CA do server
	ClientKeyPem  string                 `protobuf:"bytes,3,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	Config        *AgentConfig           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *EnrollResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *EnrollResponse) GetClientKeyPem() string {
	if x != nil {
		return x.ClientKeyPem
	}
	return ""
}

func (x *EnrollResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type OSInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Family         string                 `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"` // debian | redhat | suse | arch | alpine | windows | darwin
	Distro         string                 `protobuf:"bytes,2,opt,name=distro,proto3" json:"distro,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Arch           string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Kernel         string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	PackageManager string                 `protobuf:"bytes,6,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	InitSystem     string                 `protobuf:"bytes,7,opt,name=init_system,json=initSystem,proto3" json:"init_system,omitempty"`
	FirewallTool   string                 `protobuf:"bytes,8,opt,name=firewall_tool,json=firewallTool,proto3" json:"firewall_tool,omitempty"`
	MacSystem      string                 `protobuf:"bytes,9,opt,name=mac_system,json=macSystem,proto3" json:"mac_system,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OSInfo) Reset() {
	*x = OSInfo{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfo) ProtoMessage() {}

func (x *OSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfo.ProtoReflect.Descriptor instead.
func (*OSInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *OSInfo) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *OSInfo) GetDistro() string {
	if x != nil {
		return x.Distro
	}
	return ""
}

func (x *OSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *OSInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *OSInfo) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

func (x *OSInfo) GetInitSystem() string {
	if x != nil {
		return x.InitSystem
	}
	return ""
}

func (x *OSInfo) GetFirewallTool() string {
	if x != nil {
		return x.FirewallTool
	}
	return ""
}

func (x *OSInfo) GetMacSystem() string {
	if x != nil {
		return x.MacSystem
	}
	return ""
}

type AgentConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatSeconds int32                  `protobuf:"varint,1,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"`
	CollectJournald  bool                   `protobuf:"varint,2,opt,name=collect_journald,json=collectJournald,proto3" json:"collect_journald,omitempty"`
	CollectAuditd    bool                   `protobuf:"varint,3,opt,name=collect_auditd,json=collectAuditd,proto3" json:"collect_auditd,omitempty"`
	WatchPaths       []string               `protobuf:"bytes,4,rep,name=watch_paths,json=watchPaths,proto3" json:"watch_paths,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentConfig) GetHeartbeatSeconds() int32 {
	if x != nil {
		return x.HeartbeatSeconds
	}
	return 0
}

func (x *AgentConfig) GetCollectJournald() bool {
	if x != nil {
		return x.CollectJournald
	}
	return false
}

func (x *AgentConfig) GetCollectAuditd() bool {
	if x != nil {
		return x.CollectAuditd
	}
	return false
}

func (x *AgentConfig) GetWatchPaths() []string {
	if x != nil {
		return x.WatchPaths
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Stats         *HostStats             `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *HeartbeatRequest) GetStats() *HostStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type HostStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LoadAvg_1M     float64                `protobuf:"fixed64,1,opt,name=load_avg_1m,json=loadAvg1m,proto3" json:"load_avg_1m,omitempty"`
	MemUsedBytes   uint64                 `protobuf:"varint,2,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes  uint64                 `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	DiskUsedBytes  uint64                 `protobuf:"varint,4,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes uint64                 `protobuf:"varint,5,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	ActiveAlerts   uint32                 `protobuf:"varint,6,opt,name=active_alerts,json=activeAlerts,proto3" json:"active_alerts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostStats) Reset() {
	*x = HostStats{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStats) ProtoMessage() {}

func (x *HostStats) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStats.ProtoReflect.Descriptor instead.
func (*HostStats) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HostStats) GetLoadAvg_1M() float64 {
	if x != nil {
		return x.LoadAvg_1M
	}
	return 0
}

func (x *HostStats) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *HostStats) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *HostStats) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *HostStats) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *HostStats) GetActiveAlerts() uint32 {
	if x != nil {
		return x.ActiveAlerts
	}
	return 0
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerTs        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"`
	PendingCommands []*Command             `protobuf:"bytes,2,rep,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetServerTs() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTs
	}
	return nil
}

func (x *HeartbeatResponse) GetPendingCommands() []*Command {
	if x != nil {
		return x.PendingCommands
	}
	return nil
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_BlockIp
	//	*Command_UnblockIp
	//	*Command_RunCheck
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetBlockIp() *BlockIPCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_BlockIp); ok {
			return x.BlockIp
		}
	}
	return nil
}

func (x *Command) GetUnblockIp() *UnblockIPCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_UnblockIp); ok {
			return x.UnblockIp
		}
	}
	return nil
}

func (x *Command) GetRunCheck() *RunCheckCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_RunCheck); ok {
			return x.RunCheck
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_BlockIp struct {
	BlockIp *BlockIPCommand `protobuf:"bytes,2,opt,name=block_ip,json=blockIp,proto3,oneof"`
}

type Command_UnblockIp struct {
	UnblockIp *UnblockIPCommand `protobuf:"bytes,3,opt,name=unblock_ip,json=unblockIp,proto3,oneof"`
}

type Command_RunCheck struct {
	RunCheck *RunCheckCommand `protobuf:"bytes,4,opt,name=run_check,json=runCheck,proto3,oneof"`
}

func (*Command_BlockIp) isCommand_Payload() {}

func (*Command_UnblockIp) isCommand_Payload() {}

func (*Command_RunCheck) isCommand_Payload() {}

type BlockIPCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ip              string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockIPCommand) Reset() {
	*x = BlockIPCommand{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockIPCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockIPCommand) ProtoMessage() {}

func (x *BlockIPCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockIPCommand.ProtoReflect.Descriptor instead.
func (*BlockIPCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *BlockIPCommand) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlockIPCommand) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *BlockIPCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnblockIPCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockIPCommand) Reset() {
	*x = UnblockIPCommand{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockIPCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockIPCommand) ProtoMessage() {}

func (x *UnblockIPCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockIPCommand.ProtoReflect.Descriptor instead.
func (*UnblockIPCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *UnblockIPCommand) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RunCheckCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckId       string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCheckCommand) Reset() {
	*x = RunCheckCommand{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCheckCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCheckCommand) ProtoMessage() {}

func (x *RunCheckCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCheckCommand.ProtoReflect.Descriptor instead.
func (*RunCheckCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RunCheckCommand) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`     // sshd, auditd, nginx, ...
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"` // debug, info, warn, error, critical
	Raw           string                 `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Event) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Event) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *Event) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Stored        bool                   `protobuf:"varint,2,opt,name=stored,proto3" json:"stored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *EventAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventAck) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x13sentinelbr.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n" +
	"\rEnrollRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12+\n" +
	"\x02os\x18\x02 \x01(\v2\x1b.sentinelbr.agent.v1.OSInfoR\x02os\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\xb1\x01\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\tR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x03 \x01(\tR\fclientKeyPem\x128\n" +
	"\x06config\x18\x04 \x01(\v2 .sentinelbr.agent.v1.AgentConfigR\x06config\"\x8c\x02\n" +
	"\x06OSInfo\x12\x16\n" +
	"\x06family\x18\x01 \x01(\tR\x06family\x12\x16\n" +
	"\x06distro\x18\x02 \x01(\tR\x06distro\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12'\n" +
	"\x0fpackage_manager\x18\x06 \x01(\tR\x0epackageManager\x12\x1f\n" +
	"\vinit_system\x18\a \x01(\tR\n" +
	"initSystem\x12#\n" +
	"\rfirewall_tool\x18\b \x01(\tR\ffirewallTool\x12\x1d\n" +
	"\n" +
	"mac_system\x18\t \x01(\tR\tmacSystem\"\xad\x01\n" +
	"\vAgentConfig\x12+\n" +
	"\x11heartbeat_seconds\x18\x01 \x01(\x05R\x10heartbeatSeconds\x12)\n" +
	"\x10collect_journald\x18\x02 \x01(\bR\x0fcollectJournald\x12%\n" +
	"\x0ecollect_auditd\x18\x03 \x01(\bR\rcollectAuditd\x12\x1f\n" +
	"\vwatch_paths\x18\x04 \x03(\tR\n" +
	"watchPaths\"\x8d\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x124\n" +
	"\x05stats\x18\x03 \x01(\v2\x1e.sentinelbr.agent.v1.HostStatsR\x05stats\"\xf0\x01\n" +
	"\tHostStats\x12\x1e\n" +
	"\vload_avg_1m\x18\x01 \x01(\x01R\tloadAvg1m\x12$\n" +
	"\x0emem_used_bytes\x18\x02 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x03 \x01(\x04R\rmemTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x04 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x05 \x01(\x04R\x0ediskTotalBytes\x12#\n" +
	"\ractive_alerts\x18\x06 \x01(\rR\factiveAlerts\"\x95\x01\n" +
	"\x11HeartbeatResponse\x127\n" +
	"\tserver_ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bserverTs\x12G\n" +
	"\x10pending_commands\x18\x02 \x03(\v2\x1c.sentinelbr.agent.v1.CommandR\x0fpendingCommands\"\xf3\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\bblock_ip\x18\x02 \x01(\v2#.sentinelbr.agent.v1.BlockIPCommandH\x00R\ablockIp\x12F\n" +
	"\n" +
	"unblock_ip\x18\x03 \x01(\v2%.sentinelbr.agent.v1.UnblockIPCommandH\x00R\tunblockIp\x12C\n" +
	"\trun_check\x18\x04 \x01(\v2$.sentinelbr.agent.v1.RunCheckCommandH\x00R\brunCheckB\t\n" +
	"\apayload\"c\n" +
	"\x0eBlockIPCommand\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\"\n" +
	"\x10UnblockIPCommand\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\",\n" +
	"\x0fRunCheckCommand\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\"\xa8\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\tR\x03raw\x12>\n" +
	"\x06fields\x18\a \x03(\v2&.sentinelbr.agent.v1.Event.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\bEventAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06stored\x18\x02 \x01(\bR\x06stored2\x8c\x02\n" +
	"\fAgentService\x12Q\n" +
	"\x06Enroll\x12\".sentinelbr.agent.v1.EnrollRequest\x1a#.sentinelbr.agent.v1.EnrollResponse\x12Z\n" +
	"\tHeartbeat\x12%.sentinelbr.agent.v1.HeartbeatRequest\x1a&.sentinelbr.agent.v1.HeartbeatResponse\x12M\n" +
	"\fStreamEvents\x12\x1a.sentinelbr.agent.v1.Event\x1a\x1d.sentinelbr.agent.v1.EventAck(\x010\x01B6Z4github.com/sentinelbr/agent/internal/grpc/pb;agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_proto_goTypes = []any{
	(*EnrollRequest)(nil),         // 0: sentinelbr.agent.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 1: sentinelbr.agent.v1.EnrollResponse
	(*OSInfo)(nil),                // 2: sentinelbr.agent.v1.OSInfo
	(*AgentConfig)(nil),           // 3: sentinelbr.agent.v1.AgentConfig
	(*HeartbeatRequest)(nil),      // 4: sentinelbr.agent.v1.HeartbeatRequest
	(*HostStats)(nil),             // 5: sentinelbr.agent.v1.HostStats
	(*HeartbeatResponse)(nil),     // 6: sentinelbr.agent.v1.HeartbeatResponse
	(*Command)(nil),               // 7: sentinelbr.agent.v1.Command
	(*BlockIPCommand)(nil),        // 8: sentinelbr.agent.v1.BlockIPCommand
	(*UnblockIPCommand)(nil),      // 9: sentinelbr.agent.v1.UnblockIPCommand
	(*RunCheckCommand)(nil),       // 10: sentinelbr.agent.v1.RunCheckCommand
	(*Event)(nil),                 // 11: sentinelbr.agent.v1.Event
	(*EventAck)(nil),              // 12: sentinelbr.agent.v1.EventAck
	nil,                           // 13: sentinelbr.agent.v1.Event.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	2,  // 0: sentinelbr.agent.v1.EnrollRequest.os:type_name -> sentinelbr.agent.v1.OSInfo
	3,  // 1: sentinelbr.agent.v1.EnrollResponse.config:type_name -> sentinelbr.agent.v1.AgentConfig
	14, // 2: sentinelbr.agent.v1.HeartbeatRequest.ts:type_name -> google.protobuf.Timestamp
	5,  // 3: sentinelbr.agent.v1.HeartbeatRequest.stats:type_name -> sentinelbr.agent.v1.HostStats
	14, // 4: sentinelbr.agent.v1.HeartbeatResponse.server_ts:type_name -> google.protobuf.Timestamp
	7,  // 5: sentinelbr.agent.v1.HeartbeatResponse.pending_commands:type_name -> sentinelbr.agent.v1.Command
	8,  // 6: sentinelbr.agent.v1.Command.block_ip:type_name -> sentinelbr.agent.v1.BlockIPCommand
	9,  // 7: sentinelbr.agent.v1.Command.unblock_ip:type_name -> sentinelbr.agent.v1.UnblockIPCommand
	10, // 8: sentinelbr.agent.v1.Command.run_check:type_name -> sentinelbr.agent.v1.RunCheckCommand
	14, // 9: sentinelbr.agent.v1.Event.ts:type_name -> google.protobuf.Timestamp
	13, // 10: sentinelbr.agent.v1.Event.fields:type_name -> sentinelbr.agent.v1.Event.FieldsEntry
	0,  // 11: sentinelbr.agent.v1.AgentService.Enroll:input_type -> sentinelbr.agent.v1.EnrollRequest
	4,  // 12: sentinelbr.agent.v1.AgentService.Heartbeat:input_type -> sentinelbr.agent.v1.HeartbeatRequest
	11, // 13: sentinelbr.agent.v1.AgentService.StreamEvents:input_type -> sentinelbr.agent.v1.Event
	1,  // 14: sentinelbr.agent.v1.AgentService.Enroll:output_type -> sentinelbr.agent.v1.EnrollResponse
	6,  // 15: sentinelbr.agent.v1.AgentService.Heartbeat:output_type -> sentinelbr.agent.v1.HeartbeatResponse
	12, // 16: sentinelbr.agent.v1.AgentService.StreamEvents:output_type -> sentinelbr.agent.v1.EventAck
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*Command_BlockIp)(nil),
		(*Command_UnblockIp)(nil),
		(*Command_RunCheck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
