// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_OK          CommandStatus = 1
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 2
	CommandStatus_COMMAND_STATUS_UNSUPPORTED CommandStatus = 3 // OS/firewall nao suporta a operacao
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_OK",
		2: "COMMAND_STATUS_FAILED",
		3: "COMMAND_STATUS_UNSUPPORTED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_OK":          1,
		"COMMAND_STATUS_FAILED":      2,
		"COMMAND_STATUS_UNSUPPORTED": 3,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // token one-time gerado no server
	Os              *OSInfo                `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname        string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetOs() *OSInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                        // UUID gerado pelo server
	ClientCertPem string                 `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"` // cert assinado pela CA do server
	ClientKeyPem  string                 `protobuf:"bytes,3,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	Config        *AgentConfig           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *EnrollResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *EnrollResponse) GetClientKeyPem() string {
	if x != nil {
		return x.ClientKeyPem
	}
	return ""
}

func (x *EnrollResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type OSInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Family         string                 `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"` // debian | redhat | suse | arch | alpine | windows | darwin
	Distro         string                 `protobuf:"bytes,2,opt,name=distro,proto3" json:"distro,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Arch           string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Kernel         string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	PackageManager string                 `protobuf:"bytes,6,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	InitSystem     string                 `protobuf:"bytes,7,opt,name=init_system,json=initSystem,proto3" json:"init_system,omitempty"`
	FirewallTool   string                 `protobuf:"bytes,8,opt,name=firewall_tool,json=firewallTool,proto3" json:"firewall_tool,omitempty"`
	MacSystem      string                 `protobuf:"bytes,9,opt,name=mac_system,json=macSystem,proto3" json:"mac_system,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OSInfo) Reset() {
	*x = OSInfo{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfo) ProtoMessage() {}

func (x *OSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfo.ProtoReflect.Descriptor instead.
func (*OSInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *OSInfo) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *OSInfo) GetDistro() string {
	if x != nil {
		return x.Distro
	}
	return ""
}

func (x *OSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *OSInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *OSInfo) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

func (x *OSInfo) GetInitSystem() string {
	if x != nil {
		return x.InitSystem
	}
	return ""
}

func (x *OSInfo) GetFirewallTool() string {
	if x != nil {
		return x.FirewallTool
	}
	return ""
}

func (x *OSInfo) GetMacSystem() string {
	if x != nil {
		return x.MacSystem
	}
	return ""
}

type AgentConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatSeconds int32                  `protobuf:"varint,1,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"`
	CollectJournald  bool                   `protobuf:"varint,2,opt,name=collect_journald,json=collectJournald,proto3" json:"collect_journald,omitempty"`
	CollectAuditd    bool                   `protobuf:"varint,3,opt,name=collect_auditd,json=collectAuditd,proto3" json:"collect_auditd,omitempty"`
	WatchPaths       []string               `protobuf:"bytes,4,rep,name=watch_paths,json=watchPaths,proto3" json:"watch_paths,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentConfig) GetHeartbeatSeconds() int32 {
	if x != nil {
		return x.HeartbeatSeconds
	}
	return 0
}

func (x *AgentConfig) GetCollectJournald() bool {
	if x != nil {
		return x.CollectJournald
	}
	return false
}

func (x *AgentConfig) GetCollectAuditd() bool {
	if x != nil {
		return x.CollectAuditd
	}
	return false
}

func (x *AgentConfig) GetWatchPaths() []string {
	if x != nil {
		return x.WatchPaths
	}
	return nil
}

type HeartbeatRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	HostId string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Ts     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Stats  *HostStats             `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	// Resultados de Commands recebidos em heartbeats anteriores. Agente executa
	// localmente (firewall block, etc) e reporta no proximo tick.
	CommandResults []*CommandResult `protobuf:"bytes,4,rep,name=command_results,json=commandResults,proto3" json:"command_results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *HeartbeatRequest) GetStats() *HostStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *HeartbeatRequest) GetCommandResults() []*CommandResult {
	if x != nil {
		return x.CommandResults
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=sentinelbr.agent.v1.CommandStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // vazio se status == OK
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResult) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

type HostStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LoadAvg_1M     float64                `protobuf:"fixed64,1,opt,name=load_avg_1m,json=loadAvg1m,proto3" json:"load_avg_1m,omitempty"`
	MemUsedBytes   uint64                 `protobuf:"varint,2,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes  uint64                 `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	DiskUsedBytes  uint64                 `protobuf:"varint,4,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes uint64                 `protobuf:"varint,5,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	ActiveAlerts   uint32                 `protobuf:"varint,6,opt,name=active_alerts,json=activeAlerts,proto3" json:"active_alerts,omitempty"`
	IpAddress      string                 `protobuf:"bytes,7,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`              // IP principal do host (eth0/en0)
	CpuCount       uint32                 `protobuf:"varint,8,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`                // numero de cores logicos
	UptimeSeconds  uint64                 `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // uptime do host
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostStats) Reset() {
	*x = HostStats{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStats) ProtoMessage() {}

func (x *HostStats) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStats.ProtoReflect.Descriptor instead.
func (*HostStats) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HostStats) GetLoadAvg_1M() float64 {
	if x != nil {
		return x.LoadAvg_1M
	}
	return 0
}

func (x *HostStats) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *HostStats) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *HostStats) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *HostStats) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *HostStats) GetActiveAlerts() uint32 {
	if x != nil {
		return x.ActiveAlerts
	}
	return 0
}

func (x *HostStats) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *HostStats) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *HostStats) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerTs        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"`
	PendingCommands []*Command             `protobuf:"bytes,2,rep,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetServerTs() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTs
	}
	return nil
}

func (x *HeartbeatResponse) GetPendingCommands() []*Command {
	if x != nil {
		return x.PendingCommands
	}
	return nil
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_BlockIp
	//	*Command_UnblockIp
	//	*Command_RunCheck
	//	*Command_RunYaraScan
	//	*Command_QuarantineFile
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetBlockIp() *BlockIPCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_BlockIp); ok {
			return x.BlockIp
		}
	}
	return nil
}

func (x *Command) GetUnblockIp() *UnblockIPCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_UnblockIp); ok {
			return x.UnblockIp
		}
	}
	return nil
}

func (x *Command) GetRunCheck() *RunCheckCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_RunCheck); ok {
			return x.RunCheck
		}
	}
	return nil
}

func (x *Command) GetRunYaraScan() *RunYaraScanCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_RunYaraScan); ok {
			return x.RunYaraScan
		}
	}
	return nil
}

func (x *Command) GetQuarantineFile() *QuarantineFileCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_QuarantineFile); ok {
			return x.QuarantineFile
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_BlockIp struct {
	BlockIp *BlockIPCommand `protobuf:"bytes,2,opt,name=block_ip,json=blockIp,proto3,oneof"`
}

type Command_UnblockIp struct {
	UnblockIp *UnblockIPCommand `protobuf:"bytes,3,opt,name=unblock_ip,json=unblockIp,proto3,oneof"`
}

type Command_RunCheck struct {
	RunCheck *RunCheckCommand `protobuf:"bytes,4,opt,name=run_check,json=runCheck,proto3,oneof"`
}

type Command_RunYaraScan struct {
	RunYaraScan *RunYaraScanCommand `protobuf:"bytes,5,opt,name=run_yara_scan,json=runYaraScan,proto3,oneof"`
}

type Command_QuarantineFile struct {
	QuarantineFile *QuarantineFileCommand `protobuf:"bytes,6,opt,name=quarantine_file,json=quarantineFile,proto3,oneof"`
}

func (*Command_BlockIp) isCommand_Payload() {}

func (*Command_UnblockIp) isCommand_Payload() {}

func (*Command_RunCheck) isCommand_Payload() {}

func (*Command_RunYaraScan) isCommand_Payload() {}

func (*Command_QuarantineFile) isCommand_Payload() {}

type BlockIPCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ip              string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockIPCommand) Reset() {
	*x = BlockIPCommand{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockIPCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockIPCommand) ProtoMessage() {}

func (x *BlockIPCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockIPCommand.ProtoReflect.Descriptor instead.
func (*BlockIPCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *BlockIPCommand) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlockIPCommand) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *BlockIPCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnblockIPCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockIPCommand) Reset() {
	*x = UnblockIPCommand{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockIPCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockIPCommand) ProtoMessage() {}

func (x *UnblockIPCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockIPCommand.ProtoReflect.Descriptor instead.
func (*UnblockIPCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UnblockIPCommand) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RunCheckCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckId       string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCheckCommand) Reset() {
	*x = RunCheckCommand{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCheckCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCheckCommand) ProtoMessage() {}

func (x *RunCheckCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCheckCommand.ProtoReflect.Descriptor instead.
func (*RunCheckCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RunCheckCommand) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

type RunYaraScanCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`     // diretorio ou arquivo a escanear
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // ex: "manual_ui", "scheduled", "incident_response"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunYaraScanCommand) Reset() {
	*x = RunYaraScanCommand{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunYaraScanCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunYaraScanCommand) ProtoMessage() {}

func (x *RunYaraScanCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunYaraScanCommand.ProtoReflect.Descriptor instead.
func (*RunYaraScanCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RunYaraScanCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RunYaraScanCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type QuarantineFileCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // caminho absoluto do arquivo malicioso
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                     // ex: "yara_critical_match:WebshellPHP"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuarantineFileCommand) Reset() {
	*x = QuarantineFileCommand{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuarantineFileCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuarantineFileCommand) ProtoMessage() {}

func (x *QuarantineFileCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuarantineFileCommand.ProtoReflect.Descriptor instead.
func (*QuarantineFileCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *QuarantineFileCommand) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *QuarantineFileCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`     // sshd, auditd, nginx, ...
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"` // debug, info, warn, error, critical
	Raw           string                 `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Event) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Event) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *Event) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Stored        bool                   `protobuf:"varint,2,opt,name=stored,proto3" json:"stored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *EventAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventAck) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

type InventoryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // apt | dnf | zypper | pacman | apk
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Packages      []*PackageInfo         `protobuf:"bytes,4,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReport) Reset() {
	*x = InventoryReport{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReport) ProtoMessage() {}

func (x *InventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReport.ProtoReflect.Descriptor instead.
func (*InventoryReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *InventoryReport) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *InventoryReport) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *InventoryReport) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *InventoryReport) GetPackages() []*PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

type PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"` // amd64 | arm64 | noarch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *PackageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type InventoryAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PackagesReceived int32                  `protobuf:"varint,1,opt,name=packages_received,json=packagesReceived,proto3" json:"packages_received,omitempty"`
	ScanScheduled    bool                   `protobuf:"varint,2,opt,name=scan_scheduled,json=scanScheduled,proto3" json:"scan_scheduled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InventoryAck) Reset() {
	*x = InventoryAck{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryAck) ProtoMessage() {}

func (x *InventoryAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryAck.ProtoReflect.Descriptor instead.
func (*InventoryAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *InventoryAck) GetPackagesReceived() int32 {
	if x != nil {
		return x.PackagesReceived
	}
	return 0
}

func (x *InventoryAck) GetScanScheduled() bool {
	if x != nil {
		return x.ScanScheduled
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x13sentinelbr.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n" +
	"\rEnrollRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12+\n" +
	"\x02os\x18\x02 \x01(\v2\x1b.sentinelbr.agent.v1.OSInfoR\x02os\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\xb1\x01\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\tR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x03 \x01(\tR\fclientKeyPem\x128\n" +
	"\x06config\x18\x04 \x01(\v2 .sentinelbr.agent.v1.AgentConfigR\x06config\"\x8c\x02\n" +
	"\x06OSInfo\x12\x16\n" +
	"\x06family\x18\x01 \x01(\tR\x06family\x12\x16\n" +
	"\x06distro\x18\x02 \x01(\tR\x06distro\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12'\n" +
	"\x0fpackage_manager\x18\x06 \x01(\tR\x0epackageManager\x12\x1f\n" +
	"\vinit_system\x18\a \x01(\tR\n" +
	"initSystem\x12#\n" +
	"\rfirewall_tool\x18\b \x01(\tR\ffirewallTool\x12\x1d\n" +
	"\n" +
	"mac_system\x18\t \x01(\tR\tmacSystem\"\xad\x01\n" +
	"\vAgentConfig\x12+\n" +
	"\x11heartbeat_seconds\x18\x01 \x01(\x05R\x10heartbeatSeconds\x12)\n" +
	"\x10collect_journald\x18\x02 \x01(\bR\x0fcollectJournald\x12%\n" +
	"\x0ecollect_auditd\x18\x03 \x01(\bR\rcollectAuditd\x12\x1f\n" +
	"\vwatch_paths\x18\x04 \x03(\tR\n" +
	"watchPaths\"\xda\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x124\n" +
	"\x05stats\x18\x03 \x01(\v2\x1e.sentinelbr.agent.v1.HostStatsR\x05stats\x12K\n" +
	"\x0fcommand_results\x18\x04 \x03(\v2\".sentinelbr.agent.v1.CommandResultR\x0ecommandResults\"\xcc\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".sentinelbr.agent.v1.CommandStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12;\n" +
	"\vexecuted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\"\xd3\x02\n" +
	"\tHostStats\x12\x1e\n" +
	"\vload_avg_1m\x18\x01 \x01(\x01R\tloadAvg1m\x12$\n" +
	"\x0emem_used_bytes\x18\x02 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x03 \x01(\x04R\rmemTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x04 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x05 \x01(\x04R\x0ediskTotalBytes\x12#\n" +
	"\ractive_alerts\x18\x06 \x01(\rR\factiveAlerts\x12\x1d\n" +
	"\n" +
	"ip_address\x18\a \x01(\tR\tipAddress\x12\x1b\n" +
	"\tcpu_count\x18\b \x01(\rR\bcpuCount\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x04R\ruptimeSeconds\"\x95\x01\n" +
	"\x11HeartbeatResponse\x127\n" +
	"\tserver_ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bserverTs\x12G\n" +
	"\x10pending_commands\x18\x02 \x03(\v2\x1c.sentinelbr.agent.v1.CommandR\x0fpendingCommands\"\x99\x03\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\bblock_ip\x18\x02 \x01(\v2#.sentinelbr.agent.v1.BlockIPCommandH\x00R\ablockIp\x12F\n" +
	"\n" +
	"unblock_ip\x18\x03 \x01(\v2%.sentinelbr.agent.v1.UnblockIPCommandH\x00R\tunblockIp\x12C\n" +
	"\trun_check\x18\x04 \x01(\v2$.sentinelbr.agent.v1.RunCheckCommandH\x00R\brunCheck\x12M\n" +
	"\rrun_yara_scan\x18\x05 \x01(\v2'.sentinelbr.agent.v1.RunYaraScanCommandH\x00R\vrunYaraScan\x12U\n" +
	"\x0fquarantine_file\x18\x06 \x01(\v2*.sentinelbr.agent.v1.QuarantineFileCommandH\x00R\x0equarantineFileB\t\n" +
	"\apayload\"c\n" +
	"\x0eBlockIPCommand\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\"\n" +
	"\x10UnblockIPCommand\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\",\n" +
	"\x0fRunCheckCommand\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\"@\n" +
	"\x12RunYaraScanCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"L\n" +
	"\x15QuarantineFileCommand\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa8\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\tR\x03raw\x12>\n" +
	"\x06fields\x18\a \x03(\v2&.sentinelbr.agent.v1.Event.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\bEventAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06stored\x18\x02 \x01(\bR\x06stored\"\xbf\x01\n" +
	"\x0fInventoryReport\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12=\n" +
	"\fcollected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12<\n" +
	"\bpackages\x18\x04 \x03(\v2 .sentinelbr.agent.v1.PackageInfoR\bpackages\"O\n" +
	"\vPackageInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\"b\n" +
	"\fInventoryAck\x12+\n" +
	"\x11packages_received\x18\x01 \x01(\x05R\x10packagesReceived\x12%\n" +
	"\x0escan_scheduled\x18\x02 \x01(\bR\rscanScheduled*\x81\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COMMAND_STATUS_OK\x10\x01\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x02\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSUPPORTED\x10\x032\xe8\x02\n" +
	"\fAgentService\x12Q\n" +
	"\x06Enroll\x12\".sentinelbr.agent.v1.EnrollRequest\x1a#.sentinelbr.agent.v1.EnrollResponse\x12Z\n" +
	"\tHeartbeat\x12%.sentinelbr.agent.v1.HeartbeatRequest\x1a&.sentinelbr.agent.v1.HeartbeatResponse\x12M\n" +
	"\fStreamEvents\x12\x1a.sentinelbr.agent.v1.Event\x1a\x1d.sentinelbr.agent.v1.EventAck(\x010\x01\x12Z\n" +
	"\x0fSubmitInventory\x12$.sentinelbr.agent.v1.InventoryReport\x1a!.sentinelbr.agent.v1.InventoryAckB6Z4github.com/sentinelbr/agent/internal/grpc/pb;agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_agent_proto_goTypes = []any{
	(CommandStatus)(0),            // 0: sentinelbr.agent.v1.CommandStatus
	(*EnrollRequest)(nil),         // 1: sentinelbr.agent.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 2: sentinelbr.agent.v1.EnrollResponse
	(*OSInfo)(nil),                // 3: sentinelbr.agent.v1.OSInfo
	(*AgentConfig)(nil),           // 4: sentinelbr.agent.v1.AgentConfig
	(*HeartbeatRequest)(nil),      // 5: sentinelbr.agent.v1.HeartbeatRequest
	(*CommandResult)(nil),         // 6: sentinelbr.agent.v1.CommandResult
	(*HostStats)(nil),             // 7: sentinelbr.agent.v1.HostStats
	(*HeartbeatResponse)(nil),     // 8: sentinelbr.agent.v1.HeartbeatResponse
	(*Command)(nil),               // 9: sentinelbr.agent.v1.Command
	(*BlockIPCommand)(nil),        // 10: sentinelbr.agent.v1.BlockIPCommand
	(*UnblockIPCommand)(nil),      // 11: sentinelbr.agent.v1.UnblockIPCommand
	(*RunCheckCommand)(nil),       // 12: sentinelbr.agent.v1.RunCheckCommand
	(*RunYaraScanCommand)(nil),    // 13: sentinelbr.agent.v1.RunYaraScanCommand
	(*QuarantineFileCommand)(nil), // 14: sentinelbr.agent.v1.QuarantineFileCommand
	(*Event)(nil),                 // 15: sentinelbr.agent.v1.Event
	(*EventAck)(nil),              // 16: sentinelbr.agent.v1.EventAck
	(*InventoryReport)(nil),       // 17: sentinelbr.agent.v1.InventoryReport
	(*PackageInfo)(nil),           // 18: sentinelbr.agent.v1.PackageInfo
	(*InventoryAck)(nil),          // 19: sentinelbr.agent.v1.InventoryAck
	nil,                           // 20: sentinelbr.agent.v1.Event.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: sentinelbr.agent.v1.EnrollRequest.os:type_name -> sentinelbr.agent.v1.OSInfo
	4,  // 1: sentinelbr.agent.v1.EnrollResponse.config:type_name -> sentinelbr.agent.v1.AgentConfig
	21, // 2: sentinelbr.agent.v1.HeartbeatRequest.ts:type_name -> google.protobuf.Timestamp
	7,  // 3: sentinelbr.agent.v1.HeartbeatRequest.stats:type_name -> sentinelbr.agent.v1.HostStats
	6,  // 4: sentinelbr.agent.v1.HeartbeatRequest.command_results:type_name -> sentinelbr.agent.v1.CommandResult
	0,  // 5: sentinelbr.agent.v1.CommandResult.status:type_name -> sentinelbr.agent.v1.CommandStatus
	21, // 6: sentinelbr.agent.v1.CommandResult.executed_at:type_name -> google.protobuf.Timestamp
	21, // 7: sentinelbr.agent.v1.HeartbeatResponse.server_ts:type_name -> google.protobuf.Timestamp
	9,  // 8: sentinelbr.agent.v1.HeartbeatResponse.pending_commands:type_name -> sentinelbr.agent.v1.Command
	10, // 9: sentinelbr.agent.v1.Command.block_ip:type_name -> sentinelbr.agent.v1.BlockIPCommand
	11, // 10: sentinelbr.agent.v1.Command.unblock_ip:type_name -> sentinelbr.agent.v1.UnblockIPCommand
	12, // 11: sentinelbr.agent.v1.Command.run_check:type_name -> sentinelbr.agent.v1.RunCheckCommand
	13, // 12: sentinelbr.agent.v1.Command.run_yara_scan:type_name -> sentinelbr.agent.v1.RunYaraScanCommand
	14, // 13: sentinelbr.agent.v1.Command.quarantine_file:type_name -> sentinelbr.agent.v1.QuarantineFileCommand
	21, // 14: sentinelbr.agent.v1.Event.ts:type_name -> google.protobuf.Timestamp
	20, // 15: sentinelbr.agent.v1.Event.fields:type_name -> sentinelbr.agent.v1.Event.FieldsEntry
	21, // 16: sentinelbr.agent.v1.InventoryReport.collected_at:type_name -> google.protobuf.Timestamp
	18, // 17: sentinelbr.agent.v1.InventoryReport.packages:type_name -> sentinelbr.agent.v1.PackageInfo
	1,  // 18: sentinelbr.agent.v1.AgentService.Enroll:input_type -> sentinelbr.agent.v1.EnrollRequest
	5,  // 19: sentinelbr.agent.v1.AgentService.Heartbeat:input_type -> sentinelbr.agent.v1.HeartbeatRequest
	15, // 20: sentinelbr.agent.v1.AgentService.StreamEvents:input_type -> sentinelbr.agent.v1.Event
	17, // 21: sentinelbr.agent.v1.AgentService.SubmitInventory:input_type -> sentinelbr.agent.v1.InventoryReport
	2,  // 22: sentinelbr.agent.v1.AgentService.Enroll:output_type -> sentinelbr.agent.v1.EnrollResponse
	8,  // 23: sentinelbr.agent.v1.AgentService.Heartbeat:output_type -> sentinelbr.agent.v1.HeartbeatResponse
	16, // 24: sentinelbr.agent.v1.AgentService.StreamEvents:output_type -> sentinelbr.agent.v1.EventAck
	19, // 25: sentinelbr.agent.v1.AgentService.SubmitInventory:output_type -> sentinelbr.agent.v1.InventoryAck
	22, // [22:26] is the sub-list for method output_type
	18, // [18:22] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*Command_BlockIp)(nil),
		(*Command_UnblockIp)(nil),
		(*Command_RunCheck)(nil),
		(*Command_RunYaraScan)(nil),
		(*Command_QuarantineFile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
